/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.schoolmanagementsystem;

/**
 *
 * @author user
 */
public class SchoolManagementSystemUI extends javax.swing.JFrame {

    /**
     * Creates new form SchoolManagementSystemUI
     */
    public SchoolManagementSystemUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        StudentBtn = new javax.swing.JButton();
        AdmissionBtn = new javax.swing.JButton();
        FacultyBtn = new javax.swing.JButton();
        CourseBtn = new javax.swing.JButton();
        LibraryBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        AccountsBtn = new javax.swing.JButton();
        LeaveBtn = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(140, 213, 197));
        jInternalFrame1.setForeground(new java.awt.Color(153, 102, 255));
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setVisible(true);

        StudentBtn.setBackground(new java.awt.Color(140, 213, 197));
        StudentBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        StudentBtn.setForeground(new java.awt.Color(153, 102, 255));
        StudentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentBtn.setLabel("Student");
        StudentBtn.setName("Student"); // NOI18N
        StudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBtnActionPerformed(evt);
            }
        });

        AdmissionBtn.setBackground(new java.awt.Color(140, 213, 197));
        AdmissionBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AdmissionBtn.setForeground(new java.awt.Color(153, 102, 255));
        AdmissionBtn.setLabel("Admission");
        AdmissionBtn.setName("Admission"); // NOI18N

        FacultyBtn.setBackground(new java.awt.Color(140, 213, 197));
        FacultyBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        FacultyBtn.setForeground(new java.awt.Color(153, 102, 255));
        FacultyBtn.setLabel("Faculty");
        FacultyBtn.setName("Faculty"); // NOI18N

        CourseBtn.setBackground(new java.awt.Color(140, 213, 197));
        CourseBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        CourseBtn.setForeground(new java.awt.Color(153, 102, 255));
        CourseBtn.setLabel("Course");
        CourseBtn.setName("Course"); // NOI18N

        LibraryBtn.setBackground(new java.awt.Color(140, 213, 197));
        LibraryBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LibraryBtn.setForeground(new java.awt.Color(153, 102, 255));
        LibraryBtn.setLabel("Library");
        LibraryBtn.setName("Library"); // NOI18N

        AdminBtn.setBackground(new java.awt.Color(140, 213, 197));
        AdminBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(153, 102, 255));
        AdminBtn.setLabel("Admin");
        AdminBtn.setName("Admin"); // NOI18N

        AccountsBtn.setBackground(new java.awt.Color(140, 213, 197));
        AccountsBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AccountsBtn.setForeground(new java.awt.Color(153, 102, 255));
        AccountsBtn.setLabel("Accounts");
        AccountsBtn.setName("Accounts"); // NOI18N

        LeaveBtn.setBackground(new java.awt.Color(140, 213, 197));
        LeaveBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LeaveBtn.setForeground(new java.awt.Color(153, 102, 255));
        LeaveBtn.setLabel("Leave");
        LeaveBtn.setName("Leave"); // NOI18N

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .add(38, 38, 38)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(FacultyBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(StudentBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LibraryBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AccountsBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(AdmissionBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CourseBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AdminBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LeaveBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(StudentBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .add(AdmissionBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(FacultyBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .add(CourseBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LibraryBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .add(AdminBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AccountsBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .add(LeaveBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .add(499, 499, 499))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jInternalFrame1)
                .add(0, 0, Short.MAX_VALUE))
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolManagementSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolManagementSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolManagementSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolManagementSystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolManagementSystemUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountsBtn;
    private javax.swing.JButton AdminBtn;
    private javax.swing.JButton AdmissionBtn;
    private javax.swing.JButton CourseBtn;
    private javax.swing.JButton FacultyBtn;
    private javax.swing.JButton LeaveBtn;
    private javax.swing.JButton LibraryBtn;
    private javax.swing.JButton StudentBtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
