/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.schoolmanagementsystem;

/**
 *
 * @author user
 */
public class NewFaculty extends javax.swing.JFrame {

    /**
     * Creates new form NewFaculty
     */
    public NewFaculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        facultynameTxt = new javax.swing.JTextField();
        facultyIdTxt = new javax.swing.JTextField();
        facultycontactTxt = new javax.swing.JTextField();
        facultyaddressTxt = new javax.swing.JTextField();
        facultycourseCombobox = new javax.swing.JComboBox();
        facultytypeCombobox = new javax.swing.JComboBox();
        facultysalaryCombobox = new javax.swing.JComboBox();
        facultyjoinDatePicker = new org.jdesktop.swingx.JXDatePicker();
        CancelBtn = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel73.setBackground(new java.awt.Color(255, 0, 0));
        jLabel73.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(204, 0, 204));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Faculty Name");
        jLabel73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel74.setBackground(new java.awt.Color(255, 0, 0));
        jLabel74.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(204, 0, 204));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Faculty ID");
        jLabel74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel76.setBackground(new java.awt.Color(255, 0, 0));
        jLabel76.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 0, 204));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("Faculty Address");
        jLabel76.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel78.setBackground(new java.awt.Color(255, 0, 0));
        jLabel78.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(204, 0, 204));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("Faculty Course Under");
        jLabel78.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel79.setBackground(new java.awt.Color(255, 0, 0));
        jLabel79.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 0, 204));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Faculty Contact No.");
        jLabel79.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel80.setBackground(new java.awt.Color(255, 0, 0));
        jLabel80.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(204, 0, 204));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("Faculty Join Date");
        jLabel80.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel81.setBackground(new java.awt.Color(255, 0, 0));
        jLabel81.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(204, 0, 204));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("Faculty Type");
        jLabel81.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel82.setBackground(new java.awt.Color(255, 0, 0));
        jLabel82.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(204, 0, 204));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Faculty Salary");
        jLabel82.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        facultynameTxt.setBackground(new java.awt.Color(0, 153, 153));
        facultynameTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        facultynameTxt.setForeground(new java.awt.Color(204, 0, 204));

        facultyIdTxt.setBackground(new java.awt.Color(0, 153, 153));
        facultyIdTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        facultyIdTxt.setForeground(new java.awt.Color(204, 0, 204));

        facultycontactTxt.setBackground(new java.awt.Color(0, 153, 153));
        facultycontactTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        facultycontactTxt.setForeground(new java.awt.Color(204, 0, 204));

        facultyaddressTxt.setBackground(new java.awt.Color(0, 153, 153));
        facultyaddressTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        facultyaddressTxt.setForeground(new java.awt.Color(204, 0, 204));

        facultycourseCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Application", "Computer Science" }));

        facultytypeCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Time", "Part Time" }));

        facultysalaryCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "40,000", "60,000" }));

        CancelBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(102, 102, 102));
        CancelBtn.setText("Cancel");
        CancelBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/schoolmanagementsystem/14904095-male-student-with-a-teacher-in-classroom.jpg"))); // NOI18N

        submitBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(102, 102, 102));
        submitBtn.setText("Submit");
        submitBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyIdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyaddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultycontactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(facultycourseCombobox, 0, 329, Short.MAX_VALUE)
                                .addComponent(facultynameTxt)
                                .addComponent(facultysalaryCombobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(facultytypeCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(facultyjoinDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(facultyIdTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultynameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyaddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultycontactTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultycourseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultysalaryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(facultyjoinDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(facultytypeCombobox)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFaculty().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker;
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker1;
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker2;
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker3;
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker4;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField addressTxt1;
    private javax.swing.JTextField addressTxt2;
    private javax.swing.JTextField addressTxt3;
    private javax.swing.JTextField addressTxt4;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JTextField amountTxt1;
    private javax.swing.JTextField amountTxt2;
    private javax.swing.JTextField amountTxt3;
    private javax.swing.JTextField amountTxt4;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JButton cancelBtn2;
    private javax.swing.JButton cancelBtn3;
    private javax.swing.JButton cancelBtn4;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField contactTxt1;
    private javax.swing.JTextField contactTxt2;
    private javax.swing.JTextField contactTxt3;
    private javax.swing.JTextField contactTxt4;
    private javax.swing.JButton enrolgeneratorBtn;
    private javax.swing.JButton enrolgeneratorBtn1;
    private javax.swing.JButton enrolgeneratorBtn2;
    private javax.swing.JButton enrolgeneratorBtn3;
    private javax.swing.JButton enrolgeneratorBtn4;
    private javax.swing.JTextField facultyIdTxt;
    private javax.swing.JTextField facultyaddressTxt;
    private javax.swing.JTextField facultycontactTxt;
    private javax.swing.JComboBox facultycourseCombobox;
    private org.jdesktop.swingx.JXDatePicker facultyjoinDatePicker;
    private javax.swing.JTextField facultynameTxt;
    private javax.swing.JComboBox facultysalaryCombobox;
    private javax.swing.JComboBox facultytypeCombobox;
    private javax.swing.JTextField fathernameTxt;
    private javax.swing.JTextField fathernameTxt1;
    private javax.swing.JTextField fathernameTxt2;
    private javax.swing.JTextField fathernameTxt3;
    private javax.swing.JTextField fathernameTxt4;
    private javax.swing.JTextField formnoTxt;
    private javax.swing.JTextField formnoTxt1;
    private javax.swing.JTextField formnoTxt2;
    private javax.swing.JTextField formnoTxt3;
    private javax.swing.JTextField formnoTxt4;
    private org.jdesktop.swingx.JXDatePicker formsubmissionDatePicker;
    private org.jdesktop.swingx.JXDatePicker formsubmissionDatePicker1;
    private org.jdesktop.swingx.JXDatePicker formsubmissionDatePicker2;
    private org.jdesktop.swingx.JXDatePicker formsubmissionDatePicker3;
    private org.jdesktop.swingx.JXDatePicker formsubmissionDatePicker4;
    private javax.swing.JComboBox incomeCombobox;
    private javax.swing.JComboBox incomeCombobox1;
    private javax.swing.JComboBox incomeCombobox2;
    private javax.swing.JComboBox incomeCombobox3;
    private javax.swing.JComboBox incomeCombobox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField mothernameTxt;
    private javax.swing.JTextField mothernameTxt1;
    private javax.swing.JTextField mothernameTxt2;
    private javax.swing.JTextField mothernameTxt3;
    private javax.swing.JTextField mothernameTxt4;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JButton nextBtn2;
    private javax.swing.JButton nextBtn3;
    private javax.swing.JButton nextBtn4;
    private javax.swing.JComboBox qualificationCombobox;
    private javax.swing.JComboBox qualificationCombobox1;
    private javax.swing.JComboBox qualificationCombobox2;
    private javax.swing.JComboBox qualificationCombobox3;
    private javax.swing.JComboBox qualificationCombobox4;
    private javax.swing.JTextField stdnameTxt;
    private javax.swing.JTextField stdnameTxt1;
    private javax.swing.JTextField stdnameTxt2;
    private javax.swing.JTextField stdnameTxt3;
    private javax.swing.JTextField stdnameTxt4;
    private javax.swing.JComboBox studentclassCombobox;
    private javax.swing.JComboBox studentclassCombobox1;
    private javax.swing.JComboBox studentclassCombobox2;
    private javax.swing.JComboBox studentclassCombobox3;
    private javax.swing.JComboBox studentclassCombobox4;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
